package com.coderisk.common.enums;

public enum EvidenceType {
    TOKEN_MATCH,
    AST_STRUCTURE_MATCH,
    CANONICAL_TOKEN_MATCH,
    IDENTIFIER_MAPPING,
    CONTROL_STRUCTURE_MATCH,
    OPERATION_SEQUENCE_MATCH,
    BOUNDARY_PATTERN_MATCH,
    RARE_FRAGMENT_MATCH,
    TEMPLATE_COMMON_FRAGMENT,
    CROSSLANG_IR_MATCH,
    PARSER_WARNING,
    REVIEW_NOTE
}
